using LazurdIT.FluentOrm.Common;

[FluentTable("Tbl_Players")]
internal class Player : IFluentModel
{
    [FluentField("Fld_Player_Id", isPrimary: true, autoGenerated: true)]
    public long Id { get; set; }

    [FluentField("Fld_Player_Name")]
    public string Name { get; set; } = string.Empty;

    [FluentField("Fld_Player_Email")]
    public string Email { get; set; } = string.Empty;

    [FluentField("Fld_Player_FollowCount")]
    public int FollowCount { get; set; }

    [FluentField("Fld_Player_BirthDate", allowNull: true)]
    public DateTime? BirthDate { get; set; }
}